project:
  type: book
  output-dir: docs

book:
  title: "Data Science Foundations"
  subtitle: "A Structured Python Workflow from Raw Data to Interpretation"
  chapters:
    - index.qmd
    - 00-preface.qmd
    - 01-setting-up-environment.qmd
    - 02-load-and-explore-dataset.qmd
    - 03-data-cleaning-and-preparation.qmd
    - 04-data-wrangling-basics.qmd
    - 05-visualization-basics.qmd
    - 06-summary-statistics-and-insights.qmd
    - 06x1-complete-free-track.qmd
    - 99-appendix.qmd
    - 99-references.qmd

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    css: assets/css/cdi.css
    code-fold: false

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  working-dir: .